### Test Server
GET https://emp-management-app.onrender.com/

### Create Employee
POST https://emp-management-app.onrender.com/employee-api/employees
Content-Type: application/json

{
  "name": "Sita",
  "email": "sita@gmail.com", 
  "mobile": 9988776655,
  "designation": "Manager",
  "companyName": "XYZ Corp"
}
### Get All Employees
GET https://emp-management-app.onrender.com/employee-api/employees

### Get Employee by ID
GET https://emp-management-app.onrender.com/employee-api/employees/69ca2aab452424873a28218b

### Update Employee
PUT https://emp-management-app.onrender.com/employee-api/employees/69ca2aab452424873a28218b
Content-Type: application/json

{
  "designation": "Senior Developer"
}

### Delete Employee
DELETE https://emp-management-app.onrender.com/employee-api/employees/69ca2aab452424873a28218b